<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Invitations
 * @copyright   Copyright (c) 2012 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?> 

<?php
	$modelConfig	= $this->getConfig();
	$_helper		= $this->helper('invitations');
	$referralLink	= $_helper->getRefferalLink();
	$iviteeText 	= $_helper->getFilteredInviteeText();
	
	$fbABook = Mage::getModel('invitations/addressbooks')->getByKey('facebook');
	
	$customer = $this->getRequest()->getParam('customer');
	
	$promoPage		= $modelConfig->getPromoPage();
	
	$isGuestInvite	= $this->isGuestInvite();
	$canInvite		= $this->canInvite();
?>
<div id="invitations-front-page" class="invitations-index-index">

	<div id="invite-friends-holder-image" style="background:url();">
				<div class="left-side">
				<?php if ($promoPage['title'] ) { ?>
					<div class="title"><div><?php echo $promoPage['title'] ?></div></div>
				<?php } ?>
				<?php if ($promoPage['description'] ) { ?>
					<div class="description"><div><?php echo $promoPage['description'] ?></div></div>
				<?php } ?>
			</div>
		<img src="<?php if ($promoPage['bg_image']) echo $promoPage['bg_image']; else echo $this->getSkinUrl('images/plumrocket/invitations/invite-bg.jpg'); ?>" />
	</div>

	<div id="invite-friends-holder" class="col-main" style="background:url(<?php if ($promoPage['bg_image']) echo $promoPage['bg_image']; else echo $this->getSkinUrl('images/plumrocket/invitations/invite-bg.jpg'); ?>);">
		<div id="invite-design" class="clearfix cf">
			<div class="left-side">
				<?php if ($promoPage['title'] ) { ?>
					<div class="title"><div><?php echo $promoPage['title'] ?></div></div>
				<?php } ?>
				<?php if ($promoPage['description'] ) { ?>
					<div class="description"><div><?php echo $promoPage['description'] ?></div></div>
				<?php } ?>
			</div>
			<div class="right-side">
				<div class="over"></div>
				<div id='messages-holder' style="display:none;">
					<div id="messages" style="width:600px;"></div>
				</div>
				<?php if ($_helper->modulePlumrocketRewardpointsEnabled() && ($inviteePoints = Mage::getModel('rewards/config')->getInviteCredit())) { ?>
					<div class="page-head">
						<?php echo $this->__( 'Invite friends you get %1$s points when they get their first order', ($inviteePoints) ) ?>
					</div>
				<?php } ?>
				<div class="block">
					<h3><?php echo $this->__('Invite via email') ?></h3>
					<form id="invite-friends-form" action="<?php echo $this->getUrl('invitations/index/send') ?>">
						<table>
							<?php if ($isGuestInvite)  {  ?>
							<tr>
								<td class="form-list">
									<div class="input-box">
										<label for="guest_email" class="required"><em>*</em><?php echo $this->__('Your Email') ?>:</label>
										<input name="guest_email" id="guest_email" class="input-text required-entry validate-email" style="width: 278px;"/>
										<div id="guest_email-error" class="validation-advice" style="display:none;"><?php echo $this->__('Please enter a valid email address. For example johndoe@domain.com.') ?></div>
									</div>
								</td>
							</tr>
							<?php } ?>
							<tr>
								<td>
									<input name="contact-list" id="contact-list" value="" />
									<div style="display:none;" id="contact-list-data"></div>
									<div id="invitation-contacts-error" class="validation-advice" style="display:none;"><?php echo $this->__('Please enter one or more valid email addresses.') ?></div>
									<div id="invitation-result-error" class="validation-advice" style="display:none;"><?php echo $this->__('Please enter one or more valid email addresses.') ?></div>
								</td>
							</tr>
							<tr>
								<td>
									<textarea rows="10" name="message" id="invitation-message" <?php if (!($modelConfig->editInviteeText())) echo 'readonly="readonly"'; ?>><?php echo $iviteeText ?></textarea><br/>
									<input id="focus-input" value="" style="position: absolute; left: -10000px;"/>
									<div id="invitation-message-error" class="validation-advice" style="display:none;"><?php echo $this->__('This is a required field.') ?></div>
									<?php if ($modelConfig->editInviteeText()) { ?>
										<div style="text-align:right; color: #666;" id="invitation-message-left-chars"></div>
									<?php } ?>
								</td>
							</tr>
							<tr>
								<td class="buttons_area">
									<?php if ($this->hasEnabledBooks()) { ?>
										<button type="button" title="<?php echo $this->__('Address book') ?>" class="button" <?php if ($canInvite)	{ ?>onclick="pInvitations.goToStep1();"<?php } ?>><span><span><?php echo $this->__('Address book') ?></span></span></button>
									<?php } ?>
									<button type="button" title="<?php echo $this->__('Send Invitation') ?>" class="button <?php if ($canInvite)	{ ?>send-invitation<?php } ?>"><span><span><?php echo $this->__('Send Invitation') ?></span></span></button>
									<img src="<?php echo $this->getSkinUrl('images/plumrocket/invitations/loader.gif')?>" class="invitation-loader" />
								</td>
							</tr>
						</table>
					</form>
				</div>
				
				<?php if ($fbABook->isEnabled()) { ?>
					<div class="buttons_area h55">
						<a href="javascript: " class="invite-facebook-friends show_popup_login" id="fb2">
							<span class="facebook_logo"><span></span></span>
							<span class="facebook_text"><?php echo $this->__('INVITE YOUR FACEBOOK FRIENDS') ?></span>
						</a>
					</div>
				<?php } ?>
				
				<?php if ($modelConfig->showReferralLink()) { ?>
				<div class="block ">
					<h3><?php echo $this->__('Share your invitation link') ?></h3>
					<?php //<div class="account-box ad-account-info box"> ?>
						<div class="referral-link">
	                    	<input id="invitelink_text" readonly="readonly" type="text" onclick="this.select();" value="<?php echo $referralLink;?>">
						</div>
					<?php //</div> ?>
					<div class="clearfix cf">
						<div class="addthis_toolbox buttons_area" addthis:url="<?php echo $referralLink;?>" addthis:title="<?php echo $this->__('I just joined this store, here is an invite so you can join too.') ?>">
							<a class="addthis_button_facebook show_popup_login" title="Share on Facebook">
								<span class="facebook_logo"><span></span></span>
								<span class="facebook_text">Share</span>
	                        </a>
	                        <a class="addthis_button_twitter show_popup_login" title="Tweet This">
								<span class="twitter_logo"><span></span></span>
								<span class="twitter_text">Tweet</span>
	                        </a>
						</div>
						<?php if ($canInvite) { ?>
						<script type="text/javascript">
							var addthis_config = {
							 ui_language			: "en",
							 data_track_clickback	: false,
							 data_track_addressbar	: false
							}
						</script>
						<script type="text/javascript" src="https://s7.addthis.com/js/250/addthis_widget.js"></script>
						<?php } ?>
					</div>
					
				</div>
				<?php } ?>
			</div>
		</div>
	</div>

	<?php if ($customer) { ?>
	<div class="my-invitation">
		<h2><?php echo $this->__('My Invitations') ?></h2>

		<div class="invitations-lists-button-holder">
			<div class="h20">
				<img src="<?php echo $this->getSkinUrl('images/plumrocket/invitations/loader.gif')?>" class="invitation-loader tabs-loader"/>
			</div>
			<button id="load-open-invitations" type="button" title="<?php echo $this->__('Open Invitations') ?>" class="button in-tab active btn-cart"><span><span><?php echo $this->__('Open Invitations') ?></span></span></button>
			<button id="load-accepted-invitations" type="button" title="<?php echo $this->__('Accepted Invitations') ?>" class="button in-tab no-active btn-cart"><span><span><?php echo $this->__('Accepted Invitations') ?></span></span></button>
		</div>

		<div id="invitations-lists">
			<?php  echo $this->getLayout()->createBlock('invitations/open')->setData('customerId', $this->getRequest()->getParam('customer')->getId())->toHtml(); ?>
		</div>
	</div>
	<?php } ?>

	<div style="display:none" id="login-notification">
		<div class="login-notification-holder" style="text-align:center;">
			<h3><?php echo $this->__('Please login to invite friends.') ?></h3>
			<button  style="width: 100px;" type="button" title="<?php echo $this->__('Go to login') ?>" class="button in-tab btn-cart" onclick="window.location='<?php echo $this->helper('customer')->getLoginUrl(); ?>';">
				<span><span><?php echo $this->__('Login') ?></span></span>
			</button>
		</div>	
	</div>
</div>



<script type="text/javascript">
	if (window.popupLoginSettings) {
		popupLoginSettings.popupLoginMode = 4;
	}
	pjQuery_1_10_2(document).ready(function(){

		pjQuery_1_10_2('body').addClass('invitations-design-<?php echo Mage::getDesign()->getPackageName() ?>-<?php echo Mage::getDesign()->getTheme('template') ?>');

		if (window.popupLoginSettings && (typeof window.closePopupLogin == 'function')) { closePopupLogin(); }
		<?php if (!$canInvite)	 { ?>
			pjQuery_1_10_2('.right-side .over').height(pjQuery_1_10_2('.right-side').outerHeight()+30);
			pjQuery_1_10_2('.right-side .over, .right-side button, .right-side a').click(function(event){
				if (window.popupLoginSettings && (typeof window.showPopupLogin == 'function')) {
					return showPopupLogin();
				} else {
					pjQuery_1_10_2.fancybox({
						'content': pjQuery_1_10_2('#login-notification').html(),
						'titleShow': false,
						'overlayShow': true,
						'minHeight': 70
					});
					return false;
				}
			});
		<?php } ?>

		<?php if ($modelConfig->editInviteeText()) { ?>
		var maxInvtMsgLength = 500;
		var invtMsgArea = pjQuery_1_10_2('#invitation-message');
		if (invtMsgArea.val().length > maxInvtMsgLength) {
			maxInvtMsgLength = invtMsgArea.val().length+100;
		}

		invtMsgArea.keyup(function(e) {
			var tval = pjQuery_1_10_2(this).val(),
				tlength = tval.length,
				set = maxInvtMsgLength,
				remain = parseInt(set - tlength);
			if (remain < 0) remain = 0;
			pjQuery_1_10_2('#invitation-message-left-chars').html('('+remain+' characters left)');

			if (remain <= 0 && (e.which !== 0 || e.charCode !== 0)) {
				pjQuery_1_10_2(this).val((tval).substring(0, maxInvtMsgLength));
			}
		}).keyup();
		<?php } ?>
	
		pInvitations.setData({
			'urls' : {
				'step1'			: '<?php echo $this->getUrl('invitations/inviter/step1') ?>',
				'step2'			: '<?php echo $this->getUrl('invitations/inviter/step2') ?>',
				'step3'			: '<?php echo $this->getUrl('invitations/inviter/step3') ?>',

				'openInvitationsList'		: '<?php echo $this->getUrl('invitations/index/openInvitations') ?>',
				'acceptedInvitationsList'	: '<?php echo $this->getUrl('invitations/index/acceptedInvitations') ?>',
				'guestId'					: '<?php echo $this->getUrl('*/*/guestId') ?>'
			},
			'errorMsg' : {
				'emailOrPasswordMissing' : '<?php echo $this->__('Email or password missing!') ?>',
				'connectionError' : '<?php echo $this->__('Connection error please try later!') ?>'
			},
			'invitationsListAreaId' : 'plumrocket-ajax-load-area',
			'popupMessages'	: true
		});
		
		<?php if ($isGuestInvite) { ?>
			pInvitations.blockedShare = true;
		<?php } ?>
		
		pjQuery_1_10_2('#contact-list').tagsInput({
			'defaultText'	: '<?php echo $this->__('Add e-mail...') ?>',
			'width'			: 272,
			'height'		: 80,
			'staticHeight'	: true,
			'autosize'		: false,
			'email'			: true,
			'onRemoveTag'	: function(userName){
				pInvitations.removeFromContactList(userName)
			},
			'onAddTag'		: function(connectCode){
				pInvitations.addToContactList(connectCode);
				pjQuery_1_10_2('#contact-list_tagsinput').scrollTop(99999);
			}
		});
		
		contactListLiveaveTime = getTime();
		pjQuery_1_10_2('#contact-list_tagsinput').mouseleave(function(){
			var input = pjQuery_1_10_2('#contact-list_tag');
			if (input.hasClass('not_valid'))
			{
				var timeout = 600;
				setTimeout(function(){
					var t = getTime();
					if (t > contactListLiveaveTime + timeout)
					{
						contactListLiveaveTime = t;
						input.removeClass('not_valid').val('<?php echo $this->__('Add e-mail...') ?>').css('color', '#666666');
						pjQuery_1_10_2('#focus-input').focus();
					}
				}, timeout);			
			}
		});
		
		pjQuery_1_10_2('#contact-list_tagsinput').mouseenter(function(){
			contactListLiveaveTime = getTime();
		});
		
		pjQuery_1_10_2('#guest_email').blur(function(){
			var e	= pjQuery_1_10_2(this);
			var valid = pInvitations.validateSubmitContactList({'#guest_email' : false});
			if (valid){
				var id = pInvitations.getGuestId(e.val());
				if (id){
					pInvitations.unblockShare();
					pInvitations.updateReferralLink('g'+id);
					return;
				}
			}
			pInvitations.blockShare();
		})
		
		
		function getTime()
		{
			var d = new Date();
			return d.getTime();
		}
		
		pjQuery_1_10_2('#invite-friends-holder .send-invitation').click(function(){
			pInvitations.submitContactList();		
		});	
		pjQuery_1_10_2('#load-open-invitations').click(function(){
			pInvitations.getOpenInvitationsList()	
		});
		pjQuery_1_10_2('#load-accepted-invitations').click(function(){
			pInvitations.getAcceptedInvitationsList();	
		});
		pInvitations.changeInvitationsListPagerLinks(pInvitations.data.urls.openInvitationsList);
		
		INVITATIONS_REFERRAL_LINK = '<?php echo $referralLink ?>';
		
		<?php if ($canInvite) { ?>
			pjQuery_1_10_2('#invitelink_text, .addthis_toolbox img').click(function(event){
				if (pInvitations.isBlockedShare()){
					event.stopPropagation();
					return false;
				}
			});
		<?php } ?>
		
		<?php if ($canInvite && $fbABook->isEnabled()) { ?>
			pjQuery_1_10_2('.invite-facebook-friends').click(function(){
				
				if (pInvitations.isBlockedShare()) return false;
				
				var desc = pjQuery_1_10_2('#invitation-message').html();
				FB.init({appId: '<?php echo $fbABook->getSettingByKey('application_id') ?>', xfbml: true, cookie: true});
				if (!pInvitations.isMobile()){
					FB.ui({
					  method: 'send',
					  name: '<?php echo $this->__('Visit %s', $this->getStoreName()) ?>',
					  link: INVITATIONS_REFERRAL_LINK,
					  description : desc,
					  picture : '<?php echo $this->getLogoUrl() ?>',
					  display : 'iframe'
					});
				} else {
					FB.ui({
					  method: 'share',
					  name: '<?php echo $this->__('Visit %s', $this->getStoreName()) ?>',
					  href: INVITATIONS_REFERRAL_LINK,
					  description : desc,
					  picture : '<?php echo $this->getLogoUrl() ?>',
					  display : 'iframe'
					});
				}
			});
		<?php } ?>
	});
</script>