<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014-2016 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */

/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $_galleryImages = $this->getGalleryImages();
    $width = 500;
    list($maxHeight,$resizeAsSquare,$baseImageSize) = $this->helper('itactica_intenso/data')->getGalleryImagesHeight($_galleryImages, $_product, $width);
?>
<div class="small-12 medium-4 product-img-box hide-for-small-only columns" aria-live="polite" aria-busy="false">
    <figure>
		<?php 
		//floatval(number_format($Special_price, 2))
		if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE) {
						$baseurl = Mage::getStoreConfig(Mage_Core_Model_Url::XML_PATH_SECURE_URL);
						/* 
						$price = $_product->getPrice();
						$special = $_product->getSpecialPrice();
						$final_price = $_product->getFinalPrice();
						$price_main = (($price - $special)*100)/$price;
						$Special_price = $_product->getSpecialPrice(); 
						*/
						$price = $_product->getPrice();
						$old_price = $_product->getData('specialpricebundle');
						$offer_percentage = (($old_price - $price)*100)/$old_price; 
						if($price < $old_price){
						echo '<div class="intenso-product-label-wrapper position-top-right " style="margin-top: 8px;"><span class="intenso-product-label" style=" background-image: url('.$baseurl.'media/productlabel/image/c/i/circle-green.svg);color: #fff; padding: 19px; font-size: 16px; 
font-weight: lighter;">Säästä<br>'.floor($offer_percentage).'%</span></div>';
						}
							
						}
						?>
        <div class="product-label-placeholder" data-productid="<?php echo $_product->getId(); ?>" data-labelurl="<?php echo Mage::getBaseUrl(); ?>itactica-productlabel"></div>
        <a class="lightbox product-image" id="gallery-image" href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($baseImageSize); ?>">
            <?php
                $_img = '<img itemprop="image" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($width,$maxHeight).'" alt="'.$this->escapeHtml($this->getImageLabel()).'" width="' . $width . '" height="' . $maxHeight . '" >';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </a>
    </figure>
    <?php if (count($_galleryImages) > 1): ?>
    <?php if ($this->helper('itactica_intenso')->showGalleryImagesAsSlider()): ?>
    <section class="featured-slider featured-slider-section" data-options="animation_speed:300; min_item_width:74; fixed_width: true; swipe:1">
    <?php endif; ?>
        <ol class="more-views clearfix">
        <?php $i=1; foreach ($_galleryImages as $_image): ?>
            <?php if ($this->isGalleryImageVisible($_image)): ?>
            <li<?php if ($i==1): ?> class="item selected"<?php else: ?> class="item"<?php endif; ?>>
                <a class="lightbox" role="button" href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($resizeAsSquare[$i]); ?>" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>" data-url-medium="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($width,$maxHeight); ?>">
                    <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(68); ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" width="68" height="68">
                    <span class="a11y"><?php echo $this->__('Display Gallery Item %d', $i) ?></span>
                </a>
            </li>
            <?php endif; ?>
        <?php $i++; endforeach; ?>
        </ol>
    <?php if ($this->helper('itactica_intenso')->showGalleryImagesAsSlider()): ?>
    </section>
    <?php endif; ?>
    <?php endif; ?>
</div>
<?php echo $this->getChildHtml('after'); ?>
