<?php
/**
 * Intenso Premium Theme
 *
 * @category    design
 * @package     intenso_default
 * @copyright   Copyright (c) 2014-2016 Itactica (http://www.itactica.com)
 * @license     http://getintenso.com/license
 */
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<?php
$_helper          =  Mage::helper('catalogsearch');
$_value           = $_helper->getEscapedQueryText();
$_currentCategory = Mage::getSingleton('core/app')->getRequest()->getParam('cat');
$_currentAttribute = Mage::getSingleton('core/app')->getRequest()->getParam('attr');
$_filterType      = $this->getFilterType();
$_url             = $this->getAjaxUrl();
?>
<?php $themeHelper = Mage::helper('itactica_intenso'); ?>
<?php $smallLogo = ($this->getLogoSrcSmall()) ? $this->getLogoSrcSmall() : $this->getLogoSrc(); ?>
<?php $isStickyEnabled = $themeHelper->stickyMenuUrl(); ?>
<?php $isStoreSwitchEnabled = $themeHelper->storeSwitcher(); ?>
<header class="main-header<?php if ($themeHelper->stickyMenu()): ?> sticky-menu<?php endif; ?>">
    <?php if ($themeHelper->secMenuTop() && $themeHelper->showSecondaryMenu()): ?>
    <div class="row header-ribbon show-for-medium-up">
        <div class="small-12 columns">
            <?php echo $this->getChildHtml('currency_selector') ?>
            <?php echo $this->getChildHtml('store_language') ?>
            <?php if ($isStoreSwitchEnabled) echo $this->getChildHtml('store_switcher') ?>
            <span class="welcome-message"><?php echo $themeHelper->getAdditionalInfo(); ?></span>
            <?php echo $this->getChildHtml('sec_menu_links') ?>
        </div>
    </div>
    <?php endif; ?>
    <div class="row top-header">
        <div class="small-6 medium-4 large-3 logo-container columns">
            <a href="<?php echo $this->getUrl('') ?>">
                <img class="main-logo" src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" title="<?php echo $this->getLogoAlt() ?>" />
                <img class="main-logo-small" src="<?php echo $smallLogo ?>" alt="<?php echo $this->getLogoAlt() ?>" title="<?php echo $this->getLogoAlt() ?>" />
                <?php if (!empty($isStickyEnabled)): ?>
                <?php $stickyLogo = $this->getSkinUrl($themeHelper->stickyMenuUrl()); ?>
                <img class="main-logo-sticky" src="<?php echo $stickyLogo ?>" alt="<?php echo $this->getLogoAlt() ?>" title="<?php echo $this->getLogoAlt() ?>" />
                <?php endif; ?>
            </a>
        </div>
        <div class="small-6 medium-3 medium-push-5 large-3 large-push-6 icons-for-small columns text-right">
            <?php if (!$themeHelper->secMenuTop()): ?>
            <div class="welcome-message show-for-medium-up"><?php echo $themeHelper->getAdditionalInfo(); ?></div>
            <?php endif; ?>
            <a href="#" class="right-off-canvas-toggle show-for-small-only icon-main-menu"></a> <a href="<?php echo $this->getUrl('checkout/cart'); ?>" class="hide-for-large-up icon-cart"></a> <a href="<?php echo $this->getUrl('customer/account'); ?>" class="show-for-medium-only icon-user"></a>
        </div>
        <div class="medium-5 large-6 medium-pull-3 large-pull-3 columns">
            <?php $catalogSearchHelper =  $this->helper('catalogsearch'); ?>
            <form id="search_mini_form" action="<?php echo $_helper->getResultUrl() ?>" method="get"
    class="searchautocomplete UI-SEARCHAUTOCOMPLETE"
    data-tip="<?php echo $this->__(Mage::getStoreConfig('searchautocomplete/general/tip')) ?>"
    data-url="<?php echo $_url ?>"
    data-minchars="<?php echo Mage::getStoreConfig('searchautocomplete/general/min_chars') ?>"
    data-delay="<?php echo Mage::getStoreConfig('searchautocomplete/general/delay') ?>">
                <div class="form-search">
                    <div class="action">
                        <button class="button" title="Search" type="submit"><span aria-hidden="true" class="icon-search"></span></button>
                        <?php if (!$themeHelper->secMenuTop() && $themeHelper->showSecondaryMenu()): ?>
                            <div class="hide-for-small-only sec-menu icon-sec-menu"> 
                                <!-- Secondary menu dropdown -->
                                <div class="sec-menu-dropdown">
                                    <div class="arrow-box">
                                        <?php if ($isStoreSwitchEnabled) echo $this->getChildHtml('store_switcher') ?>
                                        <?php echo $this->getChildHtml('store_language') ?>
                                        <?php echo $this->getChildHtml('currency_selector') ?>
                                        <?php echo $this->getChildHtml('sec_menu_links') ?>
                                    </div>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
					
					<div id="search-input" class="">
					
					<input type="hidden"  id="home_url" value="<?php echo $this->getUrl('') ?>" />
					<input id="search" type="text" autocomplete="off"  name="<?php echo $_helper->getQueryParamName() ?>" value="<?php echo $_helper->getEscapedQueryText() ?>" class="input-text placeholder UI-SEARCH UI-NAV-INPUT" maxlength="<?php echo $_helper->getMaxQueryLength();?>" />
					</div>
					<div class="searchautocomplete-loader UI-LOADER">
						<div id="g01"></div>
						<div id="g02"></div>
						<div id="g03"></div>
						<div id="g04"></div>
						<div id="g05"></div>
						<div id="g06"></div>
						<div id="g07"></div>
						<div id="g08"></div>
					</div>
					<div style="display:none" id="search_autocomplete" class="UI-PLACEHOLDER search-autocomplete searchautocomplete-placeholder"></div>

                    <?php //echo $this->getChildHtml('topSearch') ?>
                </div>
            </form>
        </div>
    </div>
    <?php echo $this->getChildHtml('topMenu') ?>
<script>
	jQuery('#search').focus(function() {
    jQuery('#search-input').addClass('focus');
	}).blur(function() {
		jQuery('#search-input').removeClass('focus');
	});
</script>
</header>


