<div id="pickup_points">

    <div id="matkahuolto" class="pickup_option" style="">
        <label for="option_matkahuolto"></label>
        <select id="option_matkahuolto">
            <option value="1">Option One</option>
            <option value="2">Option Two</option>
            <option value="3">Option Three</option>
        </select>
    </div>
    
    <div id="smartpost" class="pickup_option" style="">
        <label for="option_smartpost"></label>
        <select id="option_smartpost">
            <option value="1">Option One</option>
            <option value="2">Option Two</option>
            <option value="3">Option Three</option>
        </select>
    </div>
    
    <div id="chooseapostoffice" class="pickup_option" style="">
        <label for="option_chooseapostoffice"></label>
        <select id="option_chooseapostoffice">
            <option value="1">Option One</option>
            <option value="2">Option Two</option>
            <option value="3">Option Three</option>
        </select>
    </div>
    
    <div id="closestpostoffice" class="pickup_option" style="">
        <label for="option_closestpostoffice"></label>
        <select id="option_closestpostoffice">
            <option value="1">Option One</option>
            <option value="2">Option Two</option>
            <option value="3">Option Three</option>
        </select>
    </div>

</div>

<script type="text/javascript">
     
     jQuery("#checkout-shipping-method-load > li").click(function(){
        alert('You clicked radio!');
        
    });
</script>