<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
 ?>

<div class="newspopup_up_bg" id="newspopup_up_bg_<?php echo (int)$this->getPopup()->getId(); ?>" style="display: none;">
	<?php echo $this->getChildHtml('popup.body'); ?>
</div>
<script type="text/javascript">	
	newsletterPopup.updateSettings({
		display_popup: '<?php echo $this->getPopup()->getData('display_popup'); ?>',
		delay_time: <?php echo (int)$this->getPopup()->getData('delay_time'); ?>,
		page_scroll: <?php echo (int)$this->getPopup()->getData('page_scroll'); ?>,
		css_selector: '<?php echo $this->getPopup()->getData('css_selector'); ?>',
		success_url: '<?php echo $this->getSuccessPage(); ?>',
		cookie_time_frame: <?php echo (int)$this->getPopup()->getData('cookie_time_frame'); ?>,
		id: <?php echo (int)$this->getPopup()->getId(); ?>
	});
</script>
