<?php
/**
 * MageWorx
 * MageWorx SeoExtended Extension
 *
 * @category   MageWorx
 * @package    MageWorx_SeoExtended
 * @copyright  Copyright (c) 2016 MageWorx (http://www.mageworx.com/)
 */
?>
<?php
/** @var MageWorx_SeoExtended_Helper_Data $helper */
$helper = Mage::helper('mageworx_seoextended');
?>
<script type="text/javascript">
//<![CDATA[
    SeoSuite.init({
        enteredLabel: '<?php echo $helper->__('You’ve entered <span style="font-weight:bold">0</span> character(s).') ?>',
        titleSearchUse: '<?php echo $helper->__('<br>Most search engines use up to <strong>70</strong>.') ?>',
        descriptionSearchUse: '<?php $helper->__('<br>Most search engines use up to <strong>150</strong>.') ?>'
    });
    document.observe('dom:loaded', function() {
        SeoSuite.updateForm()
    });
//]]>
</script>