<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
 ?>

<div class="field">
    <label for="<?php echo $this->getFieldId('month'); ?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->getLabel() ?></label>
    <div class="input-box customer-dob">
    <?php
        $this->setDateInput('d',
            '<div class="dob-day">
                 <input type="number" min="1" max="31" id="' . $this->getFieldId('day') . '" name="' . $this->getFieldName('day') . '" value="' . $this->getDay() . '" placeholder="'.$this->__('DD').'" title="' . $this->__('Day') . '" class="input-text validate-custom" />
                 <label for="' . $this->getFieldId('day') . '">' . $this->__('DD') . '</label>
             </div>'
        );

        $this->setDateInput('m',
            '<div class="dob-month">
                 <input type="number" min="1" max="12" id="' . $this->getFieldId('month') . '" name="' . $this->getFieldName('month') . '" value="' . $this->getMonth()  . '" placeholder="'.$this->__('MM').'" title="' . $this->__('Month')  . '" class="input-text validate-custom" />
                 <label for="' . $this->getFieldId('month') . '">' . $this->__('MM')  . '</label>
             </div>'
        );

        $this->setDateInput('y',
            '<div class="dob-year">
                 <input type="number" min="1900" id="' . $this->getFieldId('year') . '" name="' . $this->getFieldName('year') . '" value="' . $this->getYear() . '" placeholder="'.$this->__('YYYY').'" title="' . $this->__('Year')  . '" class="input-text validate-custom" />
                 <label for="' . $this->getFieldId('year') . '">' . $this->__('YYYY')  . '</label>
             </div>'
        );
    ?>
        <?php echo $this->getSortedDateInputs() ?>
        <div class="dob-full" style="display:none;">
            <input type="hidden" id="<?php echo $this->getFieldId(); ?>" name="<?php echo $this->getFieldName()?>" />
        </div>

        <div class="validation-advice" style="display:none;"></div>
    </div>
    <script type="text/javascript">
    //<![CDATA[
    if ('Varien' in window) {
        var customer_dob = new Varien.DOB('.customer-dob', <?php echo $this->isRequired() ? 'true' : 'false' ?>, '<?php echo $this->getDateFormat() ?>');
    }
    //]]>
    </script>
</div>