<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
 ?>

<div class="field">
    <label for="<?php echo $this->getFieldId(); ?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->getLabel() ?></label>
    <div class="input-box">
        <?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('gender')->getSource()->getAllOptions(false);?>
        <input type="radio" name="<?php echo $this->getFieldName()?>" title="<?php echo $this->getLabel() ?>" id="<?php echo $this->getFieldId(); ?>-female" value="<?php echo $options[1]['value']; ?>" style="vertical-align:middle;" />
        <label for="<?php echo $this->getFieldId(); ?>-female"><?php echo $this->__('Female');?></label>
        <input type="radio" name="<?php echo $this->getFieldName()?>" title="<?php echo $this->getLabel() ?>" id="<?php echo $this->getFieldId(); ?>-male" value="<?php echo $options[0]['value']; ?>" style="vertical-align:middle;" />
        <label for="<?php echo $this->getFieldId(); ?>-male"><?php echo $this->__('Male');?></label>
    </div>
</div>