<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
 ?>

<div class="field">
    <label for="<?php echo $this->getFieldId(); ?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->getLabel() ?></label>
    <div class="input-box">
    <?php if ($this->getPrefixOptions() === false): ?>
        <input type="text" id="<?php echo $this->getFieldId(); ?>" name="<?php echo $this->getFieldName()?>" value="" placeholder="<?php echo $this->getLabel(); ?>" title="<?php echo $this->getLabel() ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('prefix') ?>" />
    <?php else: ?>
        <select id="<?php echo $this->getFieldId(); ?>" name="<?php echo $this->getFieldName()?>" title="<?php echo $this->getLabel() ?>" class="<?php echo $this->helper('customer/address')->getAttributeValidationClass('prefix') ?>" >
        <?php foreach ($this->getPrefixOptions() as $_option): ?>
            <option value="<?php echo $_option?>"><?php echo $this->__($_option)?></option>
        <?php endforeach; ?>
        </select>
    <?php endif; ?>
    </div>
</div>