<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
 ?>

<div class="field">
    <label for="<?php echo $this->getFieldId(); ?>" class="required"><em>*</em><?php echo $this->getLabel();?></label>
    <div class="input-box">
        <select id="<?php echo $this->getFieldId('region_id'); ?>" name="region_id" title="<?php echo $this->getLabel();?>" class="validate-select" style="display:none;">
           <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
        </select>
        <script type="text/javascript">
        //<![CDATA[
            $('<?php echo $this->getFieldId("region_id"); ?>').setAttribute('defaultValue',  "");
        //]]>
        </script>
        <input type="text" id="<?php echo $this->getFieldId(); ?>" name="region" value="" placeholder="<?php echo $this->getLabel();?>" title="<?php echo $this->getLabel();?>" class="region-field input-text required-entry <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
    </div>
</div>